<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- ER Modeller version 4.0 schema -->
<!DOCTYPE schema [
<!ELEMENT schema (scale,left,top,width,height,id,name,notation,comment,usertype*,(entity*,atribute*,relation*,unique*,cardinality*,strong*)*)>
<!ELEMENT scale (#PCDATA)>
<!ELEMENT left (#PCDATA)>
<!ELEMENT top (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT usertype (typename, datatypedef)>
<!ELEMENT entity (left,top,width,height,id,name,comment)>
<!ELEMENT atribute (left,top,width,height,id,name,comment,datatype,arbitrary,(ent|rel))>
<!ELEMENT relation (left,top,width,height,id,name,comment)>
<!ELEMENT unique (left,top,width,height,id,name,comment,ent,atr*,primary)>
<!ELEMENT cardinality (left,top,width,height,id,name,comment,ent,rel,arbitrary,multi,glue)>
<!ELEMENT strong (left,top,width,height,ent,uni)>
<!ELEMENT datatype (#PCDATA)>
<!ELEMENT typename (#PCDATA)>
<!ELEMENT datatypedef (datatype, item*)>
<!ELEMENT item (itemname, datatype)>
<!ELEMENT itemname (#PCDATA)>
<!ELEMENT arbitrary (#PCDATA)>
<!ELEMENT ent (#PCDATA)>
<!ELEMENT rel (#PCDATA)>
<!ELEMENT atr (#PCDATA)>
<!ELEMENT primary (#PCDATA)>
<!ELEMENT multi (#PCDATA)>
<!ELEMENT glue (#PCDATA)>
<!ELEMENT uni (#PCDATA)>
]>
<schema>
	<scale>1.0</scale>
	<left>0</left>
	<top>0</top>
	<width>2500</width>
	<height>2500</height>
	<id>14</id>
	<name>Schema</name>
	<notation>0</notation>
	<comment></comment>
	<entity>
		<left>482</left>
		<top>125</top>
		<width>85</width>
		<height>39</height>
		<id>3</id>
		<name>Oddeleni</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>585</left>
		<top>99</top>
		<width>100</width>
		<height>13</height>
		<id>8</id>
		<name>cislo_oddeleni</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>1</position>
		<ent>3</ent>
	</atribute>
	<atribute>
		<left>617</left>
		<top>167</top>
		<width>105</width>
		<height>13</height>
		<id>9</id>
		<name>nazev_oddeleni</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>2</position>
		<ent>3</ent>
	</atribute>
	<cardinality>
		<left>412</left>
		<top>76</top>
		<width>63</width>
		<height>29</height>
		<id>13</id>
		<name>Oddeleni</name>
		<comment></comment>
		<ent>3</ent>
		<rel>11</rel>
		<arbitrary>false</arbitrary>
		<multi>true</multi>
		<glue>false</glue>
	</cardinality>
	<relation>
		<left>325</left>
		<top>24</top>
		<width>117</width>
		<height>39</height>
		<id>11</id>
		<name>Rel1</name>
		<comment></comment>
	</relation>
	<entity>
		<left>193</left>
		<top>119</top>
		<width>92</width>
		<height>39</height>
		<id>2</id>
		<name>Zamestnanec</name>
		<comment></comment>
		<constraints></constraints>
	</entity>
	<atribute>
		<left>215</left>
		<top>203</top>
		<width>59</width>
		<height>13</height>
		<id>6</id>
		<name>konicky</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>false</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>2</position>
		<ent>2</ent>
	</atribute>
	<atribute>
		<left>115</left>
		<top>86</top>
		<width>84</width>
		<height>13</height>
		<id>7</id>
		<name>rodne_cislo</name>
		<comment></comment>
		<datatype>Integer</datatype>
		<arbitrary>true</arbitrary>
		<primary>true</primary>
		<uniq>true</uniq>
		<position>3</position>
		<ent>2</ent>
	</atribute>
	<atribute>
		<left>133</left>
		<top>171</top>
		<width>54</width>
		<height>13</height>
		<id>5</id>
		<name>jmeno</name>
		<comment></comment>
		<datatype>VarChar2(255)</datatype>
		<arbitrary>true</arbitrary>
		<primary>false</primary>
		<uniq>false</uniq>
		<position>1</position>
		<ent>2</ent>
	</atribute>
	<cardinality>
		<left>284</left>
		<top>80</top>
		<width>89</width>
		<height>29</height>
		<id>12</id>
		<name>Zamestnanec</name>
		<comment></comment>
		<ent>2</ent>
		<rel>11</rel>
		<arbitrary>false</arbitrary>
		<multi>false</multi>
		<glue>true</glue>
	</cardinality>
</schema>
